-- Run this query in your Supabase SQL Editor to create the Telemetry table

create table
  public.voter_cards (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    election_title character varying null,
    has_name boolean null,
    total_rows smallint null,
    raw_rows jsonb null,
    constraint voter_cards_pkey primary key (id)
  ) tablespace pg_default;

-- Enable Row Level Security (RLS)
alter table public.voter_cards enable row level security;

-- Create an anonymous Insert Policy
-- This allows anyone to CREATE a row (submit telemetry), but nobody can READ the rows except you
create policy "Enable insert for anonymous users" on public.voter_cards
  as permissive
  for insert
  to anon
  with check (true);
